// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCs4g6QdZ8CUzi60N_mJSxToI3-3oggOs',
    appId: '1:721420726638:web:c92565447c5dd3b79ed17f',
    messagingSenderId: '721420726638',
    projectId: 'to-do-app-5405b',
    authDomain: 'to-do-app-5405b.firebaseapp.com',
    storageBucket: 'to-do-app-5405b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWcXecmneRnmgG1YILd9AyNnmMnIjaUds',
    appId: '1:721420726638:android:109601c016e8269c9ed17f',
    messagingSenderId: '721420726638',
    projectId: 'to-do-app-5405b',
    storageBucket: 'to-do-app-5405b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFZkYMQYi4Q_uwN2MQzyzmBjCBPQC-G_I',
    appId: '1:721420726638:ios:76337c7107546c6f9ed17f',
    messagingSenderId: '721420726638',
    projectId: 'to-do-app-5405b',
    storageBucket: 'to-do-app-5405b.appspot.com',
    iosClientId: '721420726638-7bbqpkb8h9lf1i7etq7cvvp0cp77psuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFZkYMQYi4Q_uwN2MQzyzmBjCBPQC-G_I',
    appId: '1:721420726638:ios:76337c7107546c6f9ed17f',
    messagingSenderId: '721420726638',
    projectId: 'to-do-app-5405b',
    storageBucket: 'to-do-app-5405b.appspot.com',
    iosClientId: '721420726638-7bbqpkb8h9lf1i7etq7cvvp0cp77psuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );
}
